deploy/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Sector__c</fullName>
        <label>Market Sector</label>
        <picklist>
            <picklistValues>
                <fullName>Advertising/Marketing Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services/Management Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education/Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment/Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gambling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government/Public Sector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Services/Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing/Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nonprofit/Charity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publishing/Media/Social Media/Content Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail/Wholesale Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecommunications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel/Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Design/Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Level__c</fullName>
        <inlineHelpText>Support level for the customer based on customer needs and complexity</inlineHelpText>
        <label>Service Level</label>
        <picklist>
            <picklistValues>
                <fullName>Managed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Colo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racker IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rackspace Cloud</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending A/R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dormant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sensitive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertical Marketing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Office__c</fullName>
        <description>Denotes the office that will support the customer.</description>
        <inlineHelpText>Please select the office that will support the customer.</inlineHelpText>
        <label>Support Office</label>
        <picklist>
            <picklistValues>
                <fullName>Austin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benelux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Antonio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Segment__c</fullName>
        <label>Support Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Intensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rackspace Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Colocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racker IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Only for Customer Accounts including Employees, Internal and Test</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Used for Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

deploy/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Contact Record Type</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

deploy/retrieveUnpackaged/objects/Rackspace_Contacts__c.object
<CustomObject>
    <description>Account Contact Roles   - Used for the Account  Contact Roles</description>
    <fields>
        <fullName>Rackspace_Account__c</fullName>
        <label>Rackspace Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Rackspace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rackspace_Contact__c</fullName>
        <description>Lookup for the contact that needs a role with this company.</description>
        <inlineHelpText>Used to lookup the contact to associate to the company.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Contact Roles</relationshipLabel>
        <relationshipName>Rackspace</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Abuse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NPS Contact ONLY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact Roles</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Rackspace Contacts Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/retrieveUnpackaged/classes/TestClosedWonTrigger.cls
public class TestClosedWonTrigger {
   
    static testMethod void testTrigger() {
     Boolean valid;
        Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id;
        account.Market_Sector__c = '';
        account.Support_Office__c = '';
        account.Sub_Type__c = '';
        account.Support_Segment__c = '';
        account.Service_Level__c = '';
        insert account;

        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Technical';
        insert role;

        Opportunity oldOpp = new Opportunity();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'New'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Justify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = 12;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 20000;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.EVA_Grade__c = 'B';
        oldOpp.CloseDate = System.today();
        oldOpp.Market_Sector__c = 'IS';
        oldOpp.Support_Segment__c = 'Managed';
        oldOpp.Service_Level__c = 'Intensive';
        oldOpp.Support_Office__c = 'San Antonio';
        oldOpp.Sub_Type__c = 'External';
        oldOpp.Status__c = ''; //added 9/2/2009
        insert oldOpp;

        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        valid=true;
        try {
            update oldOpp;
            update account;
        }
        
        catch (System.DmlException e) {
            
        }
    }
    
    static testMethod void testTrigger2() {
     Boolean valid;
        Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id;
        account.Market_Sector__c = '';
        account.Support_Office__c = '';
        account.Sub_Type__c = '';
        account.Support_Segment__c = '';
        account.Service_Level__c = '';
        insert account;

        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Technical';
        insert role;

        Opportunity oldOpp = new Opportunity();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'E&A Online'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Qualify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = 12;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 20000;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.CloseDate = System.today();
        oldOpp.Market_Sector__c = '';
        oldOpp.Support_Segment__c = '';
        oldOpp.Support_Office__c = '';
        oldOpp.Service_Level__c = '';
        oldOpp.Sub_Type__c = '';
        oldOpp.Status__c = ''; //added 9/2/2009
        insert oldOpp;

        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        oldOpp.Status__c = 'Needs Approval'; //added 9/2/2009
        valid=false;
        try {
            update oldOpp;
            update account;
        }
        
        catch (System.DmlException e) {
            
        }
    }
    static testMethod void testTrigger3() {
     Boolean valid;
        Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Customer'][0].Id;
        account.Market_Sector__c = '';
        account.Support_Office__c = 'Austin';
        account.Sub_Type__c = '';
        account.Support_Segment__c = 'Managed';
        account.Service_Level__c = 'Managed';
            insert account;

        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Technical';
        insert role;

        Opportunity oldOpp = new Opportunity();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'New'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Qualify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = -1;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 20000;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.CloseDate = System.today();
        oldOpp.Market_Sector__c = 'IS';
        oldOpp.Support_Segment__c = '';
        oldOpp.Service_Level__c = '';
        oldOpp.Support_Office__c = '';
        oldOpp.Sub_Type__c = 'External';
        oldOpp.Status__c = ''; //added 9/2/2009
        insert oldOpp;

        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        valid=true;
        try {
            update oldOpp;
            update account;
        }
        
        catch (System.DmlException e) {
            
        }
    }
static testMethod void testTrigger4() {
     Boolean valid;
        Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id;
        account.Market_Sector__c = 'IS';
        account.Support_Office__c = '';
        account.Sub_Type__c = '';
        account.Support_Segment__c = 'Intensive';
        account.Service_Level__c = 'Intensive';
        insert account;

        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Technical';
        insert role;

        Opportunity oldOpp = new Opportunity();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'New'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Decide';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = 12;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 20000;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.EVA_Grade__c = 'A';
        oldOpp.CloseDate = System.today();
        oldOpp.Market_Sector__c = '';
        oldOpp.Support_Segment__c = '';
        oldOpp.Service_Level__c = '';
        oldOpp.Support_Office__c = 'San Antonio';
        oldOpp.Sub_Type__c = 'External';
        oldOpp.Status__c = ''; //added 9/2/2009
        insert oldOpp;

        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        valid=true;
        try {
            update oldOpp;
            update account;
        }
        
        catch (System.DmlException e) {
            
        }
    }
    static testMethod void testTrigger5() {
     Boolean valid;
        Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id;
        account.Market_Sector__c = '';
        account.Support_Office__c = '';
        account.Sub_Type__c = '';
        account.Support_Segment__c = '';
        account.Service_Level__c = 'Managed';
        insert account;

        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Technical';
        insert role;

        Opportunity oldOpp = new Opportunity();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'New'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Justify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = 12;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 20000;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.EVA_Grade__c = 'B';
        oldOpp.CloseDate = System.today();
        oldOpp.Market_Sector__c = 'IS';
        oldOpp.Support_Segment__c = 'Managed';
        oldOpp.Service_Level__c = '';
        oldOpp.Support_Office__c = 'San Antonio';
        oldOpp.Sub_Type__c = 'External';
        oldOpp.Status__c = 'Needs Approval'; //added 9/2/2009
        insert oldOpp;

        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        valid=true;
        try {
            update oldOpp;
            update account;
        }
        
        catch (System.DmlException e) {
            
        }
    }
    static testMethod void testTrigger6() {
     Boolean valid;
        Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id;
        account.Market_Sector__c = '';
        account.Support_Office__c = '';
        account.Sub_Type__c = '';
        account.Support_Segment__c = '';
        account.Service_Level__c = 'Intensive';
        insert account;

        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        contact.MailingStreet = '123 Holiday Road';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Primary Contact';
        insert role;

        Opportunity oldOpp = new Opportunity();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'New'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Justify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = 12;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 20000;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.EVA_Grade__c = 'A';
        oldOpp.CloseDate = System.today();
        oldOpp.Market_Sector__c = 'IS';
        oldOpp.Support_Segment__c = 'Managed';
        oldOpp.Support_Office__c = 'Austin';
        oldOpp.Service_Level__c = 'Managed';
        oldOpp.Sub_Type__c = 'Internal';
        oldOpp.Status__c = ''; //added 9/2/2009
        insert oldOpp;

        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        oldOpp.Status__c = ''; //added 9/2/2009
        valid=true;
        try {
            update oldOpp;
            update account;
        }
        
        catch (System.DmlException e) {
            
        }
    }
static testMethod void testTrigger7() {
     Boolean valid;
        Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id;
        account.Market_Sector__c = '';
        account.Support_Office__c = '';
        account.Sub_Type__c = '';
        account.Support_Segment__c = '';
        account.Service_Level__c = '';
        insert account;

        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        contact.MailingStreet = '';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Technical';
        insert role;

        Opportunity oldOpp = new Opportunity();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'New'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Justify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = 12;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 20000;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.EVA_Grade__c = 'B';
        oldOpp.CloseDate = System.today();
        oldOpp.Market_Sector__c = 'IS';
        oldOpp.Support_Segment__c = 'Managed';
        oldOpp.Service_Level__c = '';
        oldOpp.Support_Office__c = 'San Antonio';
        oldOpp.Sub_Type__c = 'External';
        oldOpp.Status__c = 'Needs Approval'; //added 9/2/2009
        insert oldOpp;

        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        valid=true;
        try {
            update oldOpp;
            update account;
        }
        
        catch (System.DmlException e) {
            
        }
    }
  static testMethod void testTrigger8() {
     Boolean valid;
        Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id;
        account.Market_Sector__c = '';
        account.Support_Office__c = '';
        account.Sub_Type__c = '';
        account.Support_Segment__c = 'Managed Colocation';
        account.Service_Level__c = 'Enterprise';
        insert account;

        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        contact.MailingStreet = '123 Holiday';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Primary Contact';
        insert role;

        Opportunity oldOpp = new Opportunity();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'New'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Justify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = -1;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 100;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.EVA_Grade__c = 'B';
        oldOpp.CloseDate = System.today();
        oldOpp.Market_Sector__c = '';
        oldOpp.Support_Segment__c = 'Managed';
        oldOpp.Service_Level__c = 'Managed Colocation';
        oldOpp.Support_Office__c = '';
        oldOpp.Sub_Type__c = 'External';
        oldOpp.Status__c = ''; //added 9/2/2009
        insert oldOpp;

        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        valid=false;
        try {
            update oldOpp;
            update account;
        }
        
        catch (System.DmlException e) {
            
        }
    }
      static testMethod void testTrigger9() {
     Boolean valid;
        Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id;
        account.Market_Sector__c = '';
        account.Support_Office__c = '';
        account.Sub_Type__c = '';
        account.Support_Segment__c = '';
        insert account;

        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        contact.MailingStreet = '123 Holiday';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Primary Contact';
        insert role;

        Opportunity oldOpp = new Opportunity();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'Cloud Sales'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Justify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = -1;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 100;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.EVA_Grade__c = 'B';
        oldOpp.CloseDate = System.today();
        oldOpp.Market_Sector__c = '';
        oldOpp.Support_Segment__c = 'Rackspace Cloud';
        oldOpp.Support_Office__c = '';
        oldOpp.Service_Level__c = '';
        oldOpp.Sub_Type__c = 'External';
        oldOpp.Status__c = ''; //added 9/2/2009
        insert oldOpp;

        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        valid=false;
        try {
            update oldOpp;
            update account;
        }
        
        catch (System.DmlException e) {
            
        }
    }
}