deploy/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Sector__c</fullName>
        <label>Market Sector</label>
        <picklist>
            <picklistValues>
                <fullName>Advertising/Marketing Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services/Management Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education/Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment/Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gambling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government/Public Sector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Services/Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing/Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nonprofit/Charity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publishing/Media/Social Media/Content Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail/Wholesale Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecommunications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel/Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Design/Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending A/R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dormant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sensitive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertical Marketing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Office__c</fullName>
        <description>Denotes the office that will support the customer.</description>
        <inlineHelpText>Please select the office that will support the customer.</inlineHelpText>
        <label>Support Office</label>
        <picklist>
            <picklistValues>
                <fullName>Austin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benelux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Antonio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Segment__c</fullName>
        <label>Support Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Intensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rackspace Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Colocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racker IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Used for Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

deploy/retrieveUnpackaged/objects/LDT_Follow_Up__c.object
<CustomObject>
    <description>used to track the activities for nurture opportunities by LDT.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>LDT Follow Ups</relationshipLabel>
        <relationshipName>LDT_Follow_Ups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>status of the LDT Follow Up</description>
        <inlineHelpText>Please select the status of the follow up process.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LDT Follow Up</label>
    <nameField>
        <label>LDT Follow Up Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDT Follow Ups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/retrieveUnpackaged/classes/TestUpdateLDTOppStage.cls
public class TestUpdateLDTOppStage {

static testMethod void testTrigger() {
	 Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id;
        account.Market_Sector__c = '';
        account.Support_Office__c = '';
        account.Sub_Type__c = '';
        account.Support_Segment__c = '';
        insert account;
        
	Opportunity oldOpp = new Opportunity();
	    oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'New'][0].Id;
        oldOpp.name = 'Test Opportunity';
        oldOpp.StageName = 'Qualify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.CloseDate = System.today();
        oldOpp.Status__c = ''; //added 9/2/2009
        insert oldOpp;
     
        oldOpp.StageName = 'Sent to Nurture';
        update oldOpp;
       
       LDT_Follow_Up__c fu = [select Id from LDT_Follow_Up__c where Opportunity__c =: oldOpp.Id]; 
       fu.Status__c = 'Sent to Sales Rep';
       update fu;
        
        }
}