deploy/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to identify that this Record is not only a Customer but also a Partner</description>
        <label>Partner</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Partner Accounts</description>
        <label>Partner</label>
    </recordTypes>
</CustomObject>

deploy/retrieveUnpackaged/objects/Partner__c.object
<CustomObject>
    <description>partner custom object</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Pay Commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t pay commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit to this Opp-Acct (US only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(Cloud Reseller only)–Credit Acct/DDI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <displayFormat>CP-{0}</displayFormat>
        <label>Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/retrieveUnpackaged/classes/CustomPartner_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CustomPartner_Test {

    static testMethod void myUnitTest() {
        Account a1 = insertAccount('Test Account 1');
        Account part1 = insertPartnerAccount('Test Partner Account 1');        
        
        Opportunity o = insertOpportunity(a1, 'Test Oppty 1');
        
        Partner__c p1 = new Partner__c();
        p1.Opportunity__c = o.Id;
        p1.Partner_Account__c = part1.Id;
        p1.Role__c = 'Pay Commission';
        p1.Primary__c = false;        
        insert p1;
        
        Opportunity o1 = [SELECT Id, Partner_Opportunity__c FROM Opportunity WHERE Id=:o.Id];
        System.assertEquals(true, o1.Partner_Opportunity__c);
        
        p1.Role__c = 'Credit';
        update p1;
        
        delete p1;
        Opportunity o2 = [SELECT Id, Partner_Opportunity__c FROM Opportunity WHERE Id=:o.Id];
        System.assertEquals(false, o2.Partner_Opportunity__c);
        
        try{
            Partner__c p2 = new Partner__c();
            p2.Opportunity__c = o.Id;
            p2.Partner_Account__c = a1.Id;
            p2.Role__c = 'Pay Commission';
            p2.Primary__c = false;        
            insert p2;  //THIS SHOULD ERROR OUT b/c CAN'T ENTER OPPTY ACCOUNT AS PARTNER ACCOUNT
            System.assert(false);
        }catch (Exception e){
            System.assert(true);
        }
        
    }
    
    static Account insertAccount(String name) {
        Account a = new Account();
        a.Name = name;
        insert a;
        return a;
    }
    
    static Account insertPartnerAccount(String name) {
        RecordType PartnerAccountRT = [SELECT Id FROM RecordType WHERE sObjectType='Account' AND Name='Partner' AND IsActive=true];
        Account a = new Account();
        a.Name = name;
        a.RecordTypeId = PartnerAccountRT.Id;
        insert a;
        return a;
    }
        
    static Opportunity insertOpportunity(Account acct, String name) {
        if(acct == null) {
            acct = insertAccount(name);
        }       
        
        Opportunity o = new Opportunity();
        o.Name = name;
        o.AccountId = acct.Id;
        o.CloseDate = Date.today();
        o.StageName = 'New';        
        o.Commission_Role__c = 'Pay Commissions';
        o.OwnerId = UserInfo.getUserId();           
        
        insert o;        
        return o;
    }
}