deploy/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to identify that this Record is not only a Customer but also a Partner</description>
        <label>Partner</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Partner Accounts</description>
        <label>Partner</label>
    </recordTypes>
</CustomObject>

deploy/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Contact Record Type</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

deploy/retrieveUnpackaged/objects/Partner__c.object
<CustomObject>
    <description>partner custom object</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Pay Commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t pay commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit to this Opp-Acct (US only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(Cloud Reseller only)–Credit Acct/DDI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <displayFormat>CP-{0}</displayFormat>
        <label>Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/retrieveUnpackaged/classes/TestRackerCreatesOpportunityTrigger.cls
public class TestRackerCreatesOpportunityTrigger {
    
    static testMethod void testTrigger() {
    /*    Account account = new Account();
        account.name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Partner'][0].Id;
                account.Partner_Active__c = true;
                
            insert account;
        //added 9/2/2009
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        insert contact;*/
        
        
        Partner__c P = new Partner__c();
        P.Partner_Account__c ='0015000000TU051';
        P.Opportunity__c   = '0065000000HHsLW'; 
        P.Role__c         = 'Pay Commissions';
        
        insert P;
        
        }
        }