deploy/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Market_Sector__c</fullName>
        <label>Market Sector</label>
        <picklist>
            <picklistValues>
                <fullName>Advertising/Marketing Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services/Management Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education/Recruitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entertainment/Music</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gambling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government/Public Sector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Services/Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing/Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nonprofit/Charity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publishing/Media/Social Media/Content Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail/Wholesale Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecommunications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel/Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Design/Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Level__c</fullName>
        <inlineHelpText>Support level for the customer based on customer needs and complexity</inlineHelpText>
        <label>Service Level</label>
        <picklist>
            <picklistValues>
                <fullName>Managed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Colo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racker IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rackspace Cloud</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertical Marketing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Office__c</fullName>
        <description>Denotes the office that will support the customer.</description>
        <inlineHelpText>Please select the office that will support the customer.</inlineHelpText>
        <label>Support Office</label>
        <picklist>
            <picklistValues>
                <fullName>Austin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benelux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Antonio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Segment__c</fullName>
        <label>Support Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Intensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rackspace Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Colocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racker IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Only for Customer Accounts including Employees, Internal and Test</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Used for Prospect Accounts</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

deploy/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Contact Record Type</description>
        <label>Contact</label>
    </recordTypes>
</CustomObject>

deploy/retrieveUnpackaged/objects/Rackspace_Contacts__c.object
<CustomObject>
    <description>Account Contact Roles   - Used for the Account  Contact Roles</description>
    <fields>
        <fullName>Rackspace_Account__c</fullName>
        <label>Rackspace Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Rackspace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rackspace_Contact__c</fullName>
        <description>Lookup for the contact that needs a role with this company.</description>
        <inlineHelpText>Used to lookup the contact to associate to the company.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Contact Roles</relationshipLabel>
        <relationshipName>Rackspace</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Abuse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NPS Contact ONLY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Contact Roles</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Rackspace Contacts Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/retrieveUnpackaged/classes/TestClosedWonUtility.cls
/*
* Author: Jeremy Ross
* Purpose: Test ClosedWonUtility
* 
*/

public class TestClosedWonUtility {

    // instance variables to be used by test methods only
    private Opportunity newOpp;
    private Opportunity oldOpp;
    private Account account;
 
    
    // constructor
    public TestClosedWonUtility() {

        // instantiate stuff
    
        account = new Account();
        account.Name = 'Test Account';
        account.RecordTypeId = [Select Id from RecordType Where Name = 'Prospect'][0].Id; insert account;
        
        Contact contact = new Contact();
        contact.firstname = 'Tina';
        contact.lastname = 'Buchholtz';
        contact.phone = '2103124000';
        contact.email='tbuchhol@rackspace.com';
        insert contact;
        
        Rackspace_Contacts__c role = new Rackspace_Contacts__c();
        role.Rackspace_Account__c = account.id;
        role.Rackspace_Contact__c = contact.id;
        role.Role__c = 'Technical';
        insert role;

        
        oldOpp = new Opportunity();
        oldOpp.Name = 'Test Opportunity';
        oldOpp.StageName = 'Qualify';
        oldOpp.Probability = 0;
        oldOpp.AccountId = account.Id;
        oldOpp.Contract_Length__c = 12;
        oldOpp.Exchange_Fee__c = 234;
        oldOpp.Migration_Fees__c = 234;
        oldOpp.Hosting_Fee__c = 234;
        oldOpp.Setup_Fee__c = 234;
        oldOpp.CloseDate = System.today();
        oldOpp.RecordTypeId = [Select Id from RecordType Where Name = 'New'][0].Id;
        
        insert oldOpp;
        
        newOpp = oldOpp;
        oldOpp.StageName = 'Closed Won';
        oldOpp.Probability = 100;
        
        //insert newOpp;
    
    }

    static testMethod void testValidateStage() {
        TestClosedWonUtility harness;
        try {
            harness = new TestClosedWonUtility();
            
            // set probability to an acceptable level (>= 25)
            harness.oldOpp.Probability = 80;
            harness.oldOpp.StageName = 'Justify';
            
            Boolean result = ClosedWonUtility.validateStage(harness.oldOpp, harness.newOpp);
            
            // result should be true;
            System.assert(result);
        }
        
        finally {
            //harness.tearDown();
        }
        //try {
          //  harness = new TestClosedWonUtility();
            
            // set probability to an acceptable level (>= 25)
           // harness.oldOpp.Probability = 20;
          //  harness.oldOpp.StageName = 'Initiate';
            
          //  Boolean result = ClosedWonUtility.validateStage(harness.oldOpp, harness.newOpp);
            
            // result should be true;
           // System.assert(result);
           // }
        
       // finally {
            //harness.tearDown();
       // }
       }
        
        static testMethod void testValidateMarketSector() {
        TestClosedWonUtility harness;
        Boolean valid=true;
        try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Market_Sector__c = 'Healthcare';
            harness.oldOpp.Market_Sector__c = '';
            valid=false;
            
                        List<String> errors = new List<String>();
            Boolean result = ClosedWonUtility.validateMarketSector(harness.account,harness.newOpp,errors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.account.Market_Sector__c = '';
                        harness.oldOpp.Market_Sector__c = '';
                        valid=true;
                        List <String> errors = new List<String>();
                        Boolean result = ClosedWonUtility.validateMarketSector(harness.account,harness.newOpp,errors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
          try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Market_Sector__c = 'Healthcare';
            harness.newOpp.Market_Sector__c = 'Healthcare';
            valid=true;
                        List<String> errors = new List<String>();
            Boolean result = ClosedWonUtility.validateMarketSector(harness.account,harness.newOpp,errors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
  
       }
       
       
       static testMethod void testValidateSupportOffice() {
        TestClosedWonUtility harness;
        Boolean valid=true;
        try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Support_Office__c = 'San Antonio';
            harness.oldOpp.Support_Office__c = '';
            valid=false;
                        List<String> officeerrors = new List<String>();
            Boolean result = ClosedWonUtility.validateSupportOffice(harness.account,harness.newOpp,officeerrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.account.Support_Office__c = '';
                        harness.oldOpp.Support_Office__c = '';
                        valid=true;
                        List <String> officeerrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateSupportOffice(harness.account,harness.newOpp,officeerrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
                try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Support_Office__c = 'San Antonio';
            harness.oldOpp.Support_Office__c = '';
            valid=true;
                        List<String> officeerrors = new List<String>();
            Boolean result = ClosedWonUtility.validateSupportOffice(harness.account,harness.newOpp,officeerrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.account.Support_Office__c = '';
                        harness.oldOpp.Support_Office__c = '';
                        valid=false;
                        List <String> officeerrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateSupportOffice(harness.account,harness.newOpp,officeerrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
            }
               
      static testMethod void testValidateSubType() {
        TestClosedWonUtility harness;
        Boolean valid=true;
           try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Sub_Type__c = 'Internal Customer';
            harness.oldOpp.Sub_Type__c = '';
            valid=false;
                        List<String> suberrors = new List<String>();
            Boolean result = ClosedWonUtility.validateSubType(harness.account,harness.newOpp,suberrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.account.Sub_Type__c = '';
                        harness.oldOpp.Sub_Type__c = '';
                        valid=true;
                        List <String> suberrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateSubType(harness.account,harness.newOpp,suberrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
                try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Sub_Type__c = 'Internal Customer';
            harness.oldOpp.Sub_Type__c = '';
            valid=true;
                        List<String> suberrors = new List<String>();
            Boolean result = ClosedWonUtility.validateSubType(harness.account,harness.newOpp,suberrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.account.Sub_Type__c = '';
                        harness.oldOpp.Sub_Type__c = '';
                        valid=false;
                        List <String> suberrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateSubType(harness.account,harness.newOpp,suberrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
            }
            
         static testMethod void testValidateSupportSegment() {
        TestClosedWonUtility harness;
        Boolean valid=true;
        try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Support_Segment__c = 'Managed';
            harness.oldOpp.Support_Segment__c = '';
            valid=false;
                        List<String> segmenterrors = new List<String>();
            Boolean result = ClosedWonUtility.validateSupportSegment(harness.account,harness.newOpp,segmenterrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.account.Support_Segment__c = '';
                        harness.oldOpp.Support_Segment__c = '';
                        valid=true;
                        List <String> segmenterrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateSupportSegment(harness.account,harness.newOpp,segmenterrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
                try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Support_Segment__c = 'Managed';
            harness.oldOpp.Support_Segment__c = '';
            valid=true;
                        List<String> segmenterrors = new List<String>();
            Boolean result = ClosedWonUtility.validateSupportSegment(harness.account,harness.newOpp,segmenterrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.account.Support_Segment__c = '';
                        harness.oldOpp.Support_Segment__c = '';
                        valid=false;
                        List <String> segmenterrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateSupportSegment(harness.account,harness.newOpp,segmenterrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
            }


         static testMethod void testValidateServiceLevel() {
        TestClosedWonUtility harness;
        Boolean valid=true;
        try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Service_Level__c = 'Managed';
            harness.oldOpp.Service_Level__c = '';
            valid=false;
                        List<String> serviceerrors = new List<String>();
            Boolean result = ClosedWonUtility.validateServiceLevel(harness.account,harness.newOpp,serviceerrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.account.Service_Level__c = '';
                        harness.oldOpp.Service_Level__c = '';
                        valid=true;
                        List <String> serviceerrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateServiceLevel(harness.account,harness.newOpp,serviceerrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
                try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.account.Service_Level__c = 'Managed';
            harness.oldOpp.Service_Level__c = '';
            valid=true;
                        List<String> serviceerrors = new List<String>();
            Boolean result = ClosedWonUtility.validateServiceLevel(harness.account,harness.newOpp,serviceerrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.account.Service_Level__c = '';
                        harness.oldOpp.Service_Level__c = '';
                        valid=false;
                        List <String> serviceerrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateServiceLevel(harness.account,harness.newOpp,serviceerrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
            }


      static testMethod void testValidateContractLength() {
        TestClosedWonUtility harness;
        Boolean valid=true;
        try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.oldOpp.Contract_Length__c = 12;
            valid=false;
            List<String> contracterrors = new List<String>();
            Boolean result = ClosedWonUtility.validateContractLength(harness.newOpp,contracterrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.oldOpp.Contract_Length__c = -1;
                        valid=true;
                        List <String> contracterrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateContractLength(harness.newOpp,contracterrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
                try {
            harness = new TestClosedWonUtility();
            // set record type
            harness.oldOpp.Contract_Length__c = 12;
            valid=true;
            List<String> contracterrors = new List<String>();
            Boolean result = ClosedWonUtility.validateContractLength(harness.newOpp,contracterrors);
            // result should be true;
            System.assert(result);
        }
                finally {
            //harness.tearDown();
        }
                try {
                        harness = new TestClosedWonUtility();
                        harness.oldOpp.Contract_Length__c = -1;
                        valid=false;
                        List <String> contracterrors = new List<String>();
                        Boolean result = ClosedWonUtility.validateContractLength(harness.newOpp,contracterrors);

                        System.assert(!result);
                }
                finally {
                        //harness.tearDown();
                }
            }
            
    static testMethod void testValidateContactRoles() {
        TestClosedWonUtility harness;
        Boolean valid=true;
        try {
            harness = new TestClosedWonUtility();
            valid=false;
            List<String> errors = new List<String>();
            Boolean result = ClosedWonUtility.validateContactRoles(harness.newOpp, errors);
            
            // result should be false;
            System.assert(!result);
        }
        
        finally {
            //harness.tearDown();
        }
        try {
            harness = new TestClosedWonUtility();
            valid=true;
            List<String> errors = new List<String>();
            Boolean result = ClosedWonUtility.validateContactRoles(harness.newOpp, errors);
            
            // result should be false;
            System.assert(!result);
        }
        
        finally {
            //harness.tearDown();
        }
    }
    
    static testMethod void testUpdateAccountRecordType() {
        TestClosedWonUtility harness;
        try {
            harness = new TestClosedWonUtility();
            harness.account.RecordTypeId = '01250000000524x';
            harness.oldOpp.RecordTypeId = '012500000004x0l';
                        ClosedWonUtility.updateAccountRecordType(harness.account, harness.newOpp);
            
            // if we get here we're good
            System.assert(true);
        }
            
        finally {
            //harness.tearDown();
        }
        try {
            harness = new TestClosedWonUtility();
            harness.account.RecordTypeId = '012500000004xXf';
            harness.oldOpp.RecordTypeId = '0125000000050tK';
                        ClosedWonUtility.updateAccountRecordType(harness.account, harness.newOpp);
            
            // if we get here we're good
            System.assert(true);
        }
            
        finally {
            //harness.tearDown();
        }
         try {
            harness = new TestClosedWonUtility();
            harness.oldOpp.RecordTypeId = '0125000000059x7';
                        ClosedWonUtility.updateAccountRecordType(harness.account, harness.newOpp);
            
            // if we get here we're good
            System.assert(true);
        }
            
        finally {
            //harness.tearDown();
        }
      }
    
    static testMethod void testUpdateAccountSupportSegment() {
        TestClosedWonUtility harness;
        
        try {
            harness = new TestClosedWonUtility();
                        harness.account.Support_Segment__c = '';
                        harness.oldOpp.Support_Segment__c = 'Managed';
            ClosedWonUtility.updateAccountSupportSegment(harness.account, 'some segment');
            
            // if we get here we're good
            System.assert(true);
                        }
            
        finally {
            //harness.tearDown();
        }
    }
    
    
    static testMethod void testUpdateAccountServiceLevel() {
        TestClosedWonUtility harness;
        
        try {
            harness = new TestClosedWonUtility();
                        harness.account.Service_Level__c = '';
                        harness.oldOpp.Service_Level__c = 'Managed';
            ClosedWonUtility.UpdateAccountServiceLevel(harness.account, 'some service');
            
            // if we get here we're good
            System.assert(true);
                        }
            
        finally {
            //harness.tearDown();
        }
    }
    
    
    
    
    
    
    static testMethod void testUpdateAccountSubType() {
        TestClosedWonUtility harness;
        
        try {
            harness = new TestClosedWonUtility();
                        harness.account.Sub_Type__c = '';
                        harness.oldOpp.Sub_Type__c = 'Test';
            ClosedWonUtility.updateAccountSubType(harness.account, 'some sub-type');
            
            // if we get here we're good
            System.assert(true);
                        }
            
        finally {
            //harness.tearDown();
        }
    }
    
    static testMethod void testUpdateAccountSupportOffice() {
        TestClosedWonUtility harness;
        
        try {
            harness = new TestClosedWonUtility();
                        harness.account.Support_Office__c = '';
                        harness.oldOpp.Support_Office__c = 'Test';
            ClosedWonUtility.updateAccountSupportOffice(harness.account, 'some support office');
            
            // if we get here we're good
            System.assert(true);
                        }
            
        finally {
            //harness.tearDown();
        }
    }
    
    static testMethod void testUpdateAccountMarketSector() {
        TestClosedWonUtility harness;
        
        try {
            harness = new TestClosedWonUtility();
            harness.account.Market_Sector__c = '';
                        harness.oldOpp.Market_Sector__c = 'Adult Content';
            ClosedWonUtility.updateAccountMarketSector(harness.account, 'some sector');
            
            // if we get here we're good
            System.assert(true);
        }
            
        finally {
            //harness.tearDown();
        }
    }
    
    static testMethod void testUpdateOpportunityRecordType() {
        TestClosedWonUtility harness;
        
        try {
            harness = new TestClosedWonUtility();
            
            ClosedWonUtility.updateOpportunityRecordType(harness.newOpp);
            
            String recordTypeName  = [Select name from RecordType WHERE Id = :harness.newOpp.RecordTypeId 
            AND SObjectType = 'Opportunity'][0].name;
            
            System.assertEquals(recordTypeName, 'Read Only', 'Opportunity should have been Read'
                +' Only record type');
        }
            
        finally {
            //harness.tearDown();
        }
    }     
    }