deploy/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to identify that this Record is not only a Customer but also a Partner</description>
        <label>Partner</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>Partner Accounts</description>
        <label>Partner</label>
    </recordTypes>
</CustomObject>

deploy/retrieveUnpackaged/objects/Partner__c.object
<CustomObject>
    <description>partner custom object</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PartnerID__c</fullName>
        <description>Id of Partner (native object)</description>
        <label>PartnerID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partners</relationshipLabel>
        <relationshipName>Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Pay Commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t pay commissions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit to this Opp-Acct (US only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(Cloud Reseller only)–Credit Acct/DDI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <displayFormat>CP-{0}</displayFormat>
        <label>Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy/retrieveUnpackaged/classes/CustomPartner.cls
public class CustomPartner {    
    
    public static void addPartner(List<Partner__c> custPartnersToAdd){      
        
        List<Partner> partners = new List<Partner>();
        
        for (Integer i=0; i<custPartnersToAdd.size(); i++){     
            Partner__c custPartner = custPartnersToAdd[i];
            Partner partner = new Partner();
            partner.AccountToId = custPartner.Partner_Account__c;
            partner.OpportunityId = custPartner.Opportunity__c;
            partner.Role = custPartner.Role__c;
            partner.IsPrimary = custPartner.Primary__c;
            
            partners.add(partner);                  
        }
        
        if (partners.size() > 0 && partners != null){
            try{
                insert partners;
                
                if (partners.size() == custPartnersToAdd.size()){
                    for (Integer i=0; i<custPartnersToAdd.size(); i++){                                                         
                        custPartnersToAdd[i].PartnerID__c = partners[i].Id; 
                    }
                }
            } catch (Exception e){
                if(e.getMessage().contains('account to cannot be opportunity account')) {
                    for(Partner__c custPartner:custPartnersToAdd){
                        custPartner.addError('Partner Account cannot be Opportunity Account');
                    }
                }else{
                    for(Partner__c custPartner:custPartnersToAdd){
                        custPartner.addError(e.getMessage());
                    }
                }
            }
        }
    }
    
    public static void deletePartner(List<Partner__c> custPartnersToDelete){
        Set<Id> partnerIds = new Set<Id>();
        for (Partner__c custPartner:custPartnersToDelete){
            if (custPartner.PartnerID__c != ''){
                partnerIds.add(custPartner.PartnerID__c);
            }
        }
        
        List<Partner> partnersToDelete = [SELECT Id FROM Partner WHERE Id IN :partnerIds];
        if (partnersToDelete.size() > 0){
            delete partnersToDelete;
        }
    }

}