deploy/retrieveUnpackaged/objects/PRM_Page__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Links_Title__c</fullName>
        <label>Links Title</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Category__c</fullName>
        <label>Page Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Subcategory__c</fullName>
        <label>Page Subcategory</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <picklist>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PRM Page</label>
    <nameField>
        <label>PRM Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

deploy/retrieveUnpackaged/classes/contentCtrl.cls
public with sharing class contentCtrl {

	String category 	= '';
	String subCategory	= '';
	
	String  id;
	
	Boolean isUS;
	
	public Boolean fromSidebar;
	
	public Boolean getfromSidebar(){
		String srcStr = ApexPages.currentPage().getParameters().get('src');
		if(srcStr == 'sb'){
			return true;
		}
		return false;
	}
	
	public PRM_Page__c prmContent;

	public List<Attachment> attList;

	public PRM_Page__c getprmContent(){
		if(prmContent != null){
			return prmContent;
		}
		return null;
	}
	
	public List<Attachment> getattList(){
		attList 	= new List<Attachment>();
		attList 	= [Select id, Name, CreatedDate From Attachment Where ParentId = :id  order by LastModifiedDate desc];
		if(attList.size() > 0){
			return attList;
		}
		return null;
	}

	public contentCtrl(ApexPages.StandardController controller) {
       
       category 	= ApexPages.currentPage().getParameters().get('cat');
       subCategory	= ApexPages.currentPage().getParameters().get('subcat');
    
       UserProfileGetter upg = new UserProfileGetter();
       
       isUS = upg.isUS;
       
       if(category != null && subCategory != null){
	        List<PRM_Page__c> listPRM = new List<PRM_Page__c>();
	        listPRM = [Select id, Name, Subject__c, Page_Category__c, Page_Subcategory__c, Content__c, Links_Title__c, Version__c
	        		   From   PRM_Page__c
	        		   Where  Page_Category__c 	 = :category 
	        		    And   Page_Subcategory__c = :subCategory
	        		   Limit  2  
	        		  ];
			if(listPRM.size() > 0){
				
				if(listPRM.size() == 1){
					prmContent = listPRM[0];
				}
				
				else{
					for(PRM_Page__c prm : listPRM){
						if(prm.Version__c != null){
							if((prm.Version__c == 'US' && isUS) || (prm.Version__c == 'UK' && !isUS)){
								prmContent = prm;
							}
						}		
					}
				}
				
				id = prmContent.id;
			}       	
       }
    }

}